# Generated by Django 6.0.6 on 2026-06-07 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now=True, verbose_name='Date de consultation')),
                ('chercheur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL, verbose_name='Chercheur')),
            ],
            options={
                'verbose_name': 'Historique de consultation',
                'verbose_name_plural': 'Historiques de consultation',
                'ordering': ['-date_consultation'],
            },
        ),
    ]
