# Generated by Django 6.0.6 on 2026-06-07 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historique', '0001_initial'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueconsultation',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='missions.mission', verbose_name='Mission'),
        ),
        migrations.AlterUniqueTogether(
            name='historiqueconsultation',
            unique_together={('chercheur', 'mission')},
        ),
    ]
