# Generated by Django 6.0.6 on 2026-06-07 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('quartiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('type_date', models.CharField(choices=[('unique', 'Date unique'), ('plage', 'Plage de dates')], default='unique', max_length=10, verbose_name='Type de date')),
                ('date_unique', models.DateField(blank=True, null=True, verbose_name='Date unique')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date fin')),
                ('remuneration', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Rémunération (FCFA)')),
                ('telephone_contact', models.CharField(max_length=20, verbose_name='Téléphone de contact')),
                ('statut', models.CharField(choices=[('publiee', 'Publiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='publiee', max_length=20, verbose_name='Statut')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='categories.categorie', verbose_name='Catégorie')),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='quartiers.quartier', verbose_name='Quartier')),
                ('recruteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to=settings.AUTH_USER_MODEL, verbose_name='Recruteur')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='PhotoMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(verbose_name='Image (Cloudinary)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='missions.mission', verbose_name='Mission')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('retiree', 'Retirée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_candidature', models.DateTimeField(auto_now_add=True, verbose_name='Date de candidature')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('chercheur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL, verbose_name='Chercheur')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='missions.mission', verbose_name='Mission')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-date_candidature'],
                'unique_together': {('mission', 'chercheur')},
            },
        ),
    ]
