# Generated by Django 6.0.6 on 2026-06-07 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='remuneration',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Rémunération (FCFA)'),
        ),
    ]
