# Generated by Django 6.0.6 on 2026-06-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_alter_mission_remuneration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomission',
            name='image',
            field=models.ImageField(upload_to='missions/photos/', verbose_name='Image'),
        ),
    ]
