# Generated by Django 5.2.1 on 2026-06-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_alter_photomission_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='afficher_appel',
            field=models.BooleanField(default=False, verbose_name="Afficher le bouton d'appel"),
        ),
        migrations.AddField(
            model_name='mission',
            name='afficher_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Afficher le bouton WhatsApp'),
        ),
    ]
